CSE241: cse241
cse241: main.cpp Iterable.cpp Iterable.h GTUVector.cpp GTUVector.h GTUSet.cpp GTUSet.h GTUArray.h GTUArray.cpp
	g++ -std=c++11 -c main.cpp
	g++ -std=c++11 -c Iterable.cpp 
	g++ -std=c++11 -c GTUVector.cpp 
	g++ -std=c++11 -c GTUSet.cpp 
	g++ -std=c++11 -c GTUArray.cpp 
	g++ -std=c++11 -o output main.o Iterable.o GTUVector.o GTUSet.o GTUArray.o
	./output