CSE241: cse241
cse241: main.cpp boardgame2d.cpp boardgame2d.h eightpuzzle.cpp eightpuzzle.h klotski.cpp klotski.h pegsolitaire.cpp pegsolitaire.h 
	g++ -std=c++11 -c main.cpp
	g++ -std=c++11 -c boardgame2d.cpp
	g++ -std=c++11 -c eightpuzzle.cpp
	g++ -std=c++11 -c klotski.cpp
	g++ -std=c++11 -c pegsolitaire.cpp
	g++ -std=c++11 -o output main.o boardgame2d.o eightpuzzle.o klotski.o pegsolitaire.o
	./output